//! Immutable revision-labelled exports. Edited projections are never overwritten.
use anyhow::{Result,ensure};
use std::{fs,os::unix::fs::PermissionsExt,path::{Path,PathBuf}};
use crate::{migration::{write_new,sync_dir},store::SqliteStore};

static EXPORT_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

pub fn export(project:&Path,db:&mut SqliteStore)->Result<PathBuf> {
    let _export=EXPORT_LOCK.lock().map_err(|_|anyhow::anyhow!("projection exporter lock poisoned"))?;
    let snapshot=db.read_snapshot(None)?;
    let sources=db.imported_sources()?;
    let root=project.join(".state/projections");
    if !root.try_exists()? { fs::create_dir(&root)?; fs::set_permissions(&root,fs::Permissions::from_mode(0o700))?; }
    ensure!(fs::symlink_metadata(&root)?.is_dir(),"projection root must be a real directory");
    let dir=root.join(format!("schema-{}-revision-{}",snapshot.schema_version,snapshot.head));
    if !dir.try_exists()? { fs::create_dir(&dir)?; fs::set_permissions(&dir,fs::Permissions::from_mode(0o700))?; }
    ensure!(fs::symlink_metadata(&dir)?.is_dir(),"projection directory must be a real directory");
    let execution=if snapshot.schema_version>=7 {"External effects require controller epoch, scoped authority and resource ownership."}else{"Dispatch is blocked pending reconciliation."};
    let mut text=format!("<!-- generated by herdr-projects; runtime owner=sqlite-v2; event-head={} -->\n# Tasks\n\nRead-only projection. Preserve manual edits as an import candidate; use migration export to inspect.\nMemory remains owned by legacy Markdown. {}\n\n",snapshot.head,execution);
    for task in &snapshot.tasks { text.push_str(&format!("- {} (revision {}, {:?}): {}\n",task.id.as_str(),task.revision,task.state,task.title.replace(['\n','\r']," "))); }
    let mut runtime=serde_json::json!({"owner":"sqlite-v2","event_head":snapshot.head,"reconciliation_required":true,"sources":sources.iter().filter(|s|s.kind=="runtime"||s.kind=="thread"||s.kind=="inbox").map(|s|serde_json::json!({"path":s.path,"kind":s.kind,"digest":s.digest,"content":String::from_utf8_lossy(&s.bytes)})).collect::<Vec<_>>()});
    if snapshot.schema_version>=5 {runtime["bindings"]=serde_json::to_value(&snapshot.runtime_bindings)?;}
    if snapshot.schema_version>=6 {runtime["observations"]=serde_json::to_value(&snapshot.observations)?;}
    if snapshot.schema_version>=7 {runtime["control"]=serde_json::to_value(&snapshot.control)?;runtime["reconciliation_required"]=serde_json::json!(snapshot.control.as_ref().map(|c|c.reconciliation_required).unwrap_or(true));}
    if snapshot.schema_version>=9 {runtime["ownership"]=serde_json::to_value(&snapshot.ownership)?;}
    if snapshot.schema_version>=10 {runtime["scheduler"]=serde_json::to_value(&snapshot.scheduler)?;}
    if snapshot.schema_version>=11 {runtime["attempt_inputs"]=serde_json::to_value(&snapshot.attempt_inputs)?;runtime["cancellations"]=serde_json::to_value(&snapshot.cancellations)?;}
    if snapshot.schema_version>=13 {runtime["approvals"]=serde_json::to_value(&snapshot.approvals)?;}
    if snapshot.schema_version>=14 {runtime["budget_policies"]=serde_json::to_value(&snapshot.budget_policies)?;}
    let operations=serde_json::json!({"owner":"sqlite-v2","event_head":snapshot.head,"intents":snapshot.operations,"deliveries":snapshot.deliveries});
    let inbox=serde_json::json!({"owner":"sqlite-v2","event_head":snapshot.head,"items":snapshot.inbox});
    for (name,bytes) in [("TASKS.md",text.into_bytes()),("runtime.json",serde_json::to_vec_pretty(&runtime)?),("operations.json",serde_json::to_vec_pretty(&operations)?),("inbox.json",serde_json::to_vec_pretty(&inbox)?)] {
        let path=dir.join(name);
        if fs::symlink_metadata(&path).is_ok() { use std::io::Read;
            use std::os::unix::fs::OpenOptionsExt;
            let file=fs::OpenOptions::new().read(true).custom_flags(libc::O_NOFOLLOW|libc::O_NONBLOCK).open(&path)?;
            ensure!(file.metadata()?.is_file(),"projection is not a regular file");
            let mut existing=Vec::new(); file.take(bytes.len() as u64+1).read_to_end(&mut existing)?;
            ensure!(existing==bytes,"edited projection preserved at {}; export/import review required",path.display()); }
        else {
            let temporary=dir.join(format!(".{name}.{}.next",std::process::id()));
            if fs::symlink_metadata(&temporary).is_ok() {
                ensure!(fs::symlink_metadata(&temporary)?.is_file(),"invalid projection temporary file");
                fs::remove_file(&temporary)?;
            }
            write_new(&temporary,&bytes)?;
            // Link publishes the complete inode only if the destination is absent.
            // A concurrent manual edit can never be overwritten by this export.
            fs::hard_link(&temporary,&path)?; fs::remove_file(&temporary)?;
        }
    }
    sync_dir(&dir)?; sync_dir(&root)?; Ok(dir)
}
